-libraryjars /usr/local/lib/mmapi.jar:/usr/local/lib/midpapi20.jar:/usr/local/lib/wma11.jar:/usr/local/lib/cldcapi11.jar
-injars /home/mikeh/j2mewtk/2.5.2/apps/FPDemo/bin/FPDemo.jar
-outjar /tmp/FPDemo.jar
-keep public class * extends javax.microedition.midlet.MIDlet 
